services:
  redis:
    container_name: redis-server
    image: redis:7.2.6
    ports:
      - "6379:6379"
    build:
      args:
        SAVE: --save 60
    volumes:
      - redis-data:/data

volumes:
  redis-data:
