# Generated by Django 5.1.2 on 2024-10-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
